server.port=5000

# H2 Database Config
spring.datasource.url=jdbc:h2:file:./data/event_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Uploads Configuration
app.upload.dir=./uploads

# Security JWT Secret Key
app.jwt.secret=smart-event-management-super-secret-key-java-spring-boot-2026-key-spec
app.jwt.expiration-ms=86400000

# Multipart File Limits
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB
